export default {
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: false,
  semi: true,
  experimentalTernaries: false,
  singleQuote: true,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  trailingComma: 'none',
  singleAttributePerLine: true,
  htmlWhitespaceSensitivity: 'ignore',
  vueIndentScriptAndStyle: false,
  proseWrap: 'preserve',
  insertPragma: false,
  printWidth: 80,
  requirePragma: false,
  tabWidth: 2,
  useTabs: false,
  embeddedLanguageFormatting: 'auto',
  cursorOffset: -1
}
